# Generated by Django 4.2 on 2023-04-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_city_trip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='City',
        ),
    ]
