# Generated by Django 4.2 on 2023-04-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_trip_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
