# Generated by Django 4.2 on 2023-04-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_city_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='companions',
        ),
        migrations.DeleteModel(
            name='Companion',
        ),
    ]
