# Generated by Django 4.2 on 2023-04-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='users',
            new_name='friends',
        ),
        migrations.RemoveField(
            model_name='city',
            name='friends',
        ),
    ]
