# Generated by Django 4.2 on 2023-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_users_userprofile_friends_remove_city_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
